### ISSUE TITLE
<AP> New FW & APP for RC500S

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Firmware-Issue#1]
Please ensure the latest APP & FW for RC500S in June will: 
- update menu string
- fix SSID( Wi-Fi name cannot be changed)
- modify voice notification (western voices) 
- cancel auto recording
- exclude the speed camera warning at distance of 200M 
- include the frequency option for 50Hz, Flicker reduction.

**Comment by dod-pm1** [comment]
Updates:
All above items will be fixed EXCEPT "auto recording".
We have came up with an solution to actually make auto recording work, but this requires longer testing as this is more complicated function.
Auto recording function will be updated more likely in July/Aug update.

**Comment by DOD-AP-Sales** [comment]
If the current functionality  of auto-recording cannot behave itself, why not cancel it now?
If it is fixed, then recover it in July/Aug.

**Comment by dod-pm1** [comment]
RC500S fw is scheduled to be released by RD in end of this month.
Which then Paul and I will need to confirm, and release date for sales will be first week of July.
However, this is the worst case, we will try to bring this up earlier than scheduled.

**Comment by dod-pm1** [comment]
FW has been release, APP is estimated to be mid July.
