### ISSUE TITLE
<AP> A0P 60fps & 30fps included

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Firmware-Issue#2]
The version released on June 9th contains AU traffic camera alert info but the real resolution can only be set to 27.5fps instead of 30fps/60fps. Please make those options available for LS475W(30fps/60fps), LS475W+(30fps/60fps), and LS500W (30fps).

**Comment by dod-pm1** [comment]
No no, you misunderstood this, 27.5 we are talking about LED frequency here, NOT our shooting fps.
The resolution setting remains as 30fps/60fps, your shooting fps will be modified into 27.5fps/45fps to fit local LED frequency.
Therefore, no need to worry about this.
