### ISSUE TITLE
<NA> LS500W White Screen

### ISSUE THREAD

**Issue by DOD-NA-SALES** [dod-taiwan/Firmware-Issue#3]
Issue: During Daytime recording, the front camera slowly gets over exposure and eventually becomes white screen, but LS500W without rear camera works normally.

FW version: LS500W CB160513-1706010 69G2 EN11 A00

Here is the videos for your reference
https://drive.google.com/file/d/0B-3cO1yH51cOMktXWmlRalpzdGs/view?usp=sharing  

Note: Alll the information above have been passed to Gino. Judy will bring the 1pcs LS500W returned from NA to Shenzhen on 6/26.

**Comment by dod-pm1** [comment]
TEST firmware has been sent, lets see if the customer can still remake the issue.
The issue was not able to be copy 100%, happens potentially.
But do please try the FW out first, and we will see how it goes.

**Comment by DOD-NA-SALES** [comment]
According to Andy, he tried two days, and didn't find the white screen issue. It seems like it is fixed.
