### ISSUE TITLE
<AP>RC500S Front cam's image rotation along with mirrored effect?

### ISSUE THREAD

**Issue by DOD-AP-Sales** [dod-taiwan/Firmware-Issue#9]
RC500S user is having the latest FW 20170703 and the LG G4 Android 6.
前鏡頭翻轉之後居然還跟著變成鏡像(左右也跟著顛倒), 無論連接後鏡頭與否。
後鏡頭翻轉沒問題。
今早去金經理那驗證，確認該客所說無誤。
請RD本月務必盡快修正！
客人還投書到論壇如下:
https://dashcamtalk.com/forum/threads/dod-rc500s-firmware-update-5-7-2017.29774/

**Comment by dod-pm1** [comment]
Confirmed, this is being solved as we speak.
not APP's problem but our FW's.
Will try to solve this ASAP.

**Comment by DOD-AP-Sales** [comment]
New FW got it solved.
